# Generated by Django 3.0.4 on 2020-03-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mobile_number',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
